name: Publish Typedoc to Github Pages
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TypeStrong/typedoc-action@v1
        with:
          args: --entrypoints src/index.js
          github-token: ${{ secrets.GITHUB_TOKEN }}